<?php

declare(strict_types=1);

/**
 * ViteAssetBundle.php
 *
 * PHP Version 8.3+
 *
 * @author Philippe Gaultier <philippe@blackcube.io>
 * @copyright 2010-2026 Blackcube
 * @license https://blackcube.io/license
 */

namespace Blackcube\Assets;

use Yiisoft\Assets\AssetBundle;

/**
 * Base asset bundle for Vite-built assets.
 *
 * Reads assets-catalog.json generated by vite-manifest-plugin.
 *
 * Usage:
 *   final class AppViteAsset extends ViteAssetBundle
 *   {
 *       public ?string $basePath = '@assets';
 *       public ?string $baseUrl = '@assetsUrl';
 *       public ?string $sourcePath = '@vite/dist';
 *   }
 *
 * @author Philippe Gaultier <philippe@blackcube.io>
 * @copyright 2010-2026 Blackcube
 * @license https://blackcube.io/license
 */
class ViteAssetBundle extends AssetBundle implements ManifestAssetBundleInterface
{
    /**
     * Catalog filename relative to sourcePath.
     */
    public string $catalogFile = 'assets-catalog.json';

    /**
     * Default JS options for Vite (ES modules).
     */
    public array $jsOptions = [
        'type' => 'module',
        'defer' => true,
    ];

    /**
     * @inheritDoc
     */
    public function getCatalogFile(): string
    {
        return $this->catalogFile;
    }

    /**
     * @inheritDoc
     */
    public function loadFromCatalog(array $catalog): void
    {
        foreach ($catalog as $entry) {
            if (isset($entry['js'])) {
                $this->js[] = $entry['js'];
            }
            if (isset($entry['css'])) {
                $this->css[] = $entry['css'];
            }
        }
    }
}
