<?php

declare(strict_types=1);

/**
 * WebpackAssetBundle.php
 *
 * PHP Version 8.4
 *
 * @author Philippe Gaultier <philippe@blackcube.io>
 * @copyright 2010-2026 Blackcube - Philippe Gaultier
 * @license https://www.blackcube.io/license
 */

namespace Blackcube\Assets;

use Yiisoft\Assets\AssetBundle;
use Yiisoft\View\WebView;

/**
 * Base asset bundle for Webpack-built assets.
 *
 * Reads assets-catalog.json generated by assets-webpack-plugin.
 * If $bundles is empty, all entries from the catalog are loaded automatically
 * with webpack-standard ordering: manifest first, then vendors, then the rest.
 *
 * Usage:
 *   class AppWebpackAsset extends WebpackAssetBundle
 *   {
 *       public ?string $basePath = '@assets';
 *       public ?string $baseUrl = '@assetsUrl';
 *       public ?string $sourcePath = '@webpack/build';
 *   }
 *
 * @author Philippe Gaultier <philippe@blackcube.io>
 * @copyright 2010-2026 Blackcube - Philippe Gaultier
 * @license https://www.blackcube.io/license
 */
class WebpackAssetBundle extends AssetBundle implements ManifestAssetBundleInterface
{

    public ?int $jsPosition = WebView::POSITION_HEAD;

    public array $jsOptions = [
        'defer' => 'defer',
    ];
    /**
     * Catalog filename relative to sourcePath.
     */
    public string $catalogFile = 'assets-catalog.json';

    /**
     * Webpack bundle names to include, in order.
     * If empty, all bundles from catalog are loaded with standard ordering.
     *
     * @var string[]
     */
    public array $bundles = [];

    /**
     * Priority bundles loaded first when auto-detecting from catalog.
     * Order matters: these are loaded in array order before other bundles.
     *
     * @var string[]
     */
    protected array $priorityBundles = ['manifest', 'vendors'];

    /**
     * Bundle names that should only include CSS (no JS).
     *
     * @var string[]
     */
    public array $cssOnly = [];

    /**
     * Bundle names that should only include JS (no CSS).
     *
     * @var string[]
     */
    public array $jsOnly = [];

    /**
     * @inheritDoc
     */
    public function getCatalogFile(): string
    {
        return $this->catalogFile;
    }

    /**
     * @inheritDoc
     */
    public function loadFromCatalog(array $catalog): void
    {
        $bundles = $this->resolveBundles($catalog);

        foreach ($bundles as $bundleName) {
            if (isset($catalog[$bundleName]) === false) {
                continue;
            }

            $entry = $catalog[$bundleName];

            if (isset($entry['js']) === true && in_array($bundleName, $this->cssOnly, true) === false) {
                $this->js[] = $entry['js'];
            }

            if (isset($entry['css']) === true && in_array($bundleName, $this->jsOnly, true) === false) {
                $this->css[] = $entry['css'];
            }
        }
    }

    /**
     * Resolve bundle names to load from catalog.
     * If $bundles is explicitly set, use it as-is.
     * Otherwise, auto-detect from catalog with priority ordering.
     *
     * @param array<string, array{js?: string, css?: string}> $catalog
     * @return string[]
     */
    protected function resolveBundles(array $catalog): array
    {
        if (empty($this->bundles) === false) {
            return $this->bundles;
        }

        $bundles = [];

        foreach ($this->priorityBundles as $priorityBundle) {
            if (isset($catalog[$priorityBundle]) === true) {
                $bundles[] = $priorityBundle;
            }
        }

        foreach (array_keys($catalog) as $bundleName) {
            if (in_array($bundleName, $this->priorityBundles, true) === false) {
                $bundles[] = $bundleName;
            }
        }

        return $bundles;
    }
}
